osx_image: xcode10.2
language: objective-c

notifications:
  email: false

branches:
  only:
  - master

cache: cocoapods
podfile: Podfile

before_install:
    - gem install cocoapods --no-document --quiet
    - gem install xcpretty --no-document --quiet
    - pod --version
    - pod repo update --silent
    - xcpretty --version
    - xcodebuild -version
    - xcodebuild -showsdks

jobs:
  include:
    - stage: Lint
      name: "Einstein pod lint"
      script: 
        - pod lib lint --allow-warnings
    - stage: Clean
      script: 
        - rm -rf ~/Library/Developer/Xcode/DerivedData/
    - stage: iOS_Test
      script: 
        - cd Demo        
        - pod install
        - xcodebuild clean test -workspace Demo.xcworkspace -scheme 'Demo' -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone XS' -configuration Debug | xcpretty -c
    - stage: MacOS_Test
      script: 
        - cd ../MacDemo
        - pod install
        - xcodebuild clean test -workspace Demo.xcworkspace -scheme 'Demo' -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone XS' -configuration Debug | xcpretty -c
    - stage: deploy
      provider: script
      script: ./scripts/push.sh
      on: 
        tags: true


# script:
#   - echo Pod
#   - pod lib lint --allow-warnings

#   - echo Clean DerivedData
#   - rm -rf ~/Library/Developer/Xcode/DerivedData/

#   - cd Demo
#   - pod install
#   - xcodebuild clean test -workspace Demo.xcworkspace -scheme 'Demo' -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone XS' -configuration Debug | xcpretty -c
#   - cd ../MacDemo
#   - xcodebuild clean test -workspace MacDemo.xcworkspace -scheme 'MacDemo' -destination 'platform=macOS,arch=x86_64' -configuration Debug -UseModernBuildSystem=NO CODE_SIGNING_ALLOWED=NO | xcpretty -c



# deploy:
#   provider: script
#   script: ./scripts/push.sh
#   on:
#     tags: true
