osx_image: xcode10.2
language: objective-c

notifications:
  email: false

branches:
  only:
  - master

cache: cocoapods
podfile: Podfile

before_install:
    - gem install cocoapods --no-document --quiet
    - gem install xcpretty --no-document --quiet
    - pod --version
    - pod repo update --silent
    - xcpretty --version
    - xcodebuild -version
    - xcodebuild -showsdks

script:
  - echo Pod
  - pod lib lint --allow-warnings
  - pod install

  - echo Clean DerivedData
  - rm -rf ~/Library/Developer/Xcode/DerivedData/

  - cd Demo
  - pod install
  - xcodebuild clean
  - xcodebuild test -workspace SDWebImage.xcworkspace -scheme 'Demo' -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6' -configuration Debug | xcpretty -c
