osx_image: xcode10.2
language: objective-c
xcode_workspace: Demo/Demo.xcworkspace
xcode_scheme: Demo
xcode_destination: platform=iOS Simulator,name=iPhone 6

branches:
  only:
  - master
  
# Build with tests
script:
- pod repo update
- pod lib lint --allow-warnings
- cd Demo
- pod install
- xcodebuild clean
- xcodebuild test