osx_image: xcode10.2
language: objective-c

notifications:
  email: false

branches:
  only:
  - master
  - /^\d+\.\d+\.\d+$/

cache: cocoapods

before_install:
  - gem install cocoapods -v '~> 1.7.0' --no-document --quiet
  - gem install xcpretty --no-document --quiet
  - pod --version
  - pod repo update --silent
  - xcpretty --version
  - xcodebuild -version
  - xcodebuild -showsdks

jobs:
  include:
    - stage: lint
      script:
        - pod lib lint --allow-warnings

    - stage: test
      script:
        - rm -rf ~/Library/Developer/Xcode/DerivedData/
        - cd Demo
        - pod install
        - xcodebuild clean test -workspace Demo.xcworkspace -scheme 'Demo' -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone XS' -configuration Debug | xcpretty -c
        - cd ../MacDemo
        - pod install
        - xcodebuild clean test -workspace Demo.xcworkspace -scheme 'Demo' -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone XS' -configuration Debug | xcpretty -c
    
    - stage: deploy
      if: tag IS present
      before_script:
        - echo 'current tag -> $TRAVIS_TAG'
        - sed -i '' "s/s.version = '0.0.1'/s.version = '$TRAVIS_TAG'/g" Einstein.podspec
      script:
        - set -eo pipefail
        - pod trunk push --verbose --allow-warnings | ruby -e 'ARGF.each{ print "." }'

    - stage: Documentation
      if: tag IS present
      install: gem install jazzy --no-document --quiet
      script:
        - cd ./Jazzy
        - jazzy
        - cd ./docs
        - git init
        - git config user.name "xcodeyang"
        - git config user.email "xcodeyang@gmail.com"
        - git add .
        - git commit -m "Update blogs"
        - git push --force --quiet "https://${gh_token}@${gh_repo}" master:gh-pages

env:
 global:
  - gh_repo: github.com/ZhipingYang/Einstein.git






