# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'UITestHelper/Share', :path => '../'

  target 'DemoTests' do
    inherit! :search_paths
    pod 'UITestHelper', :path => '../'
  end

  target 'DemoUITests' do
    pod 'UITestHelper', :path => '../'
  end

end
